<a href="https://colab.research.google.com/github/fajsef9/Movie-EDA/blob/main/Movie_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub

path = kagglehub.dataset_download("tmdb/tmdb-movie-metadata/")

print(path)

Using Colab cache for faster access to the 'tmdb-movie-metadata' dataset.
/kaggle/input/tmdb-movie-metadata

In [44]:
import pandas as pd
import numpy as np

In [ ]:
import os

os.listdir(path)

['tmdb_5000_movies.csv', 'tmdb_5000_credits.csv']

In [ ]:
movie_data = pd.read_csv(path + "/tmdb_5000_movies.csv")
movie_data.describe()
movie_data.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [ ]:
credits_data = pd.read_csv(path + "/tmdb_5000_movies.csv")
credits_data.shape
credits_data.head()

(4803, 20)

In [25]:
movie_data.isnull().sum().sort_values(ascending=False)

homepage                3091
tagline                  844
overview                   3
runtime                    2
release_date               1
id                         0
budget                     0
genres                     0
original_title             0
popularity                 0
original_language          0
keywords                   0
production_countries       0
production_companies       0
spoken_languages           0
revenue                    0
status                     0
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [28]:
movie_data.duplicated().sum()
movie_data.dtypes

budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
status                   object
tagline                  object
title                    object
vote_average            float64
vote_count                int64
dtype: object

In [29]:
movie_data = movie_data.drop(columns=["homepage"])

In [31]:
movie_data.isnull().sum().sort_values(ascending=False)

tagline                 844
overview                  3
runtime                   2
release_date              1
id                        0
budget                    0
genres                    0
original_title            0
popularity                0
original_language         0
keywords                  0
production_countries      0
production_companies      0
spoken_languages          0
revenue                   0
status                    0
title                     0
vote_average              0
vote_count                0
dtype: int64

In [33]:
(movie_data == 0).sum().sort_values(ascending=False)

revenue                 1427
budget                  1037
vote_average              63
vote_count                62
runtime                   35
popularity                 1
genres                     0
id                         0
keywords                   0
original_title             0
original_language          0
release_date               0
production_countries       0
production_companies       0
overview                   0
status                     0
spoken_languages           0
title                      0
tagline                    0
dtype: int64

In [34]:
print("Budget zeros:", (movie_data["budget"] == 0).sum())
print("Revenue zeros:", (movie_data["revenue"] == 0).sum())

Budget zeros: 1037
Revenue zeros: 1427

In [35]:
movie_data[movie_data["budget"] == 0][["title", "budget", "revenue"]].head(10)

                                      title  budget    revenue
265                      The Cat in the Hat       0          0
321                            The Campaign       0  104907746
359  Alvin and the Chipmunks: The Road Chip       0  233755553
406                        Arthur Christmas       0          0
409                           All That Jazz       0   37823676
453                        The Pink Panther       0          0
463                                 Déjà Vu       0          0
474                               Evolution       0          0
475                                The Edge       0   43312294
489                                  Oceans       0   19406406

In [45]:
movie_data["budget"] = movie_data["budget"].replace(0, np.nan)
movie_data["revenue"] = movie_data["revenue"].replace(0, np.nan)

In [37]:
movie_data[["budget", "revenue"]].isnull().sum()

budget     1037
revenue    1427
dtype: int64

In [38]:
zero_counts = (movie_data == 0).sum()

zero_counts[zero_counts > 0]

popularity       1
runtime         35
vote_average    63
vote_count      62
dtype: int64

In [39]:
movie_data[movie_data["vote_average"] == 0][
    ["title", "vote_average", "vote_count"]
].head(20)

                              title  vote_average  vote_count
1464            Black Water Transit           0.0           0
3669           Should've Been Romeo           0.0           0
3670                Running Forever           0.0           0
3852                     The Secret           0.0           0
3855                 Time to Choose           0.0           0
3960                   The Deported           0.0           0
3967            Four Single Fathers           0.0           0
4051                         8 Days           0.0           0
4065                     Mi America           0.0           0
4068                      Sharkskin           0.0           0
4118         Hum To Mohabbat Karega           0.0           0
4140    To Be Frank, Sinatra at 100           0.0           0
4186    A Beginner's Guide to Snuff           0.0           0
4210            Dil Jo Bhi Kahey...           0.0           0
4266  House at the End of the Drive           0.0           0
4269  The Ballad of Gregorio Cortez           0.0           0
4275         Queen of the Mountains           0.0           0
4293                   The Algerian           0.0           0
4305      Down & Out With The Dolls           0.0           0
4307           Certifiably Jonathan           0.0           0

In [40]:
movie_data[movie_data["vote_count"] == 0][
    ["title", "vote_average", "vote_count"]
].head(20)

                              title  vote_average  vote_count
1464            Black Water Transit           0.0           0
3669           Should've Been Romeo           0.0           0
3670                Running Forever           0.0           0
3852                     The Secret           0.0           0
3855                 Time to Choose           0.0           0
3960                   The Deported           0.0           0
3967            Four Single Fathers           0.0           0
4051                         8 Days           0.0           0
4065                     Mi America           0.0           0
4068                      Sharkskin           0.0           0
4118         Hum To Mohabbat Karega           0.0           0
4140    To Be Frank, Sinatra at 100           0.0           0
4186    A Beginner's Guide to Snuff           0.0           0
4210            Dil Jo Bhi Kahey...           0.0           0
4266  House at the End of the Drive           0.0           0
4269  The Ballad of Gregorio Cortez           0.0           0
4275         Queen of the Mountains           0.0           0
4293                   The Algerian           0.0           0
4305      Down & Out With The Dolls           0.0           0
4307           Certifiably Jonathan           0.0           0

In [41]:
movie_data[movie_data["runtime"] == 0][
    ["title", "runtime"]
].head(20)

                          title  runtime
1011            The Tooth Fairy      0.0
3112    Blood Done Sign My Name      0.0
3669       Should've Been Romeo      0.0
3809        How to Fall in Love      0.0
3953                 Fort McCoy      0.0
3992                  Sardaarji      0.0
4068                  Sharkskin      0.0
4118     Hum To Mohabbat Karega      0.0
4205                   N-Secure      0.0
4210        Dil Jo Bhi Kahey...      0.0
4241                  The Salon      0.0
4313                 Below Zero      0.0
4318            Bleeding Hearts      0.0
4322         Sex With Strangers      0.0
4328      The Vatican Exorcisms      0.0
4405          Karachi se Lahore      0.0
4435  The Horror Network Vol. 1      0.0
4458        Harrison Montgomery      0.0
4502              Water & Power      0.0
4504    Light from the Darkroom      0.0

In [42]:
movie_data[movie_data["popularity"] == 0][
    ["title", "popularity"]
]

                           title  popularity
4553  America Is Still the Place         0.0

In [46]:
movie_data["runtime"] = movie_data["runtime"].replace(0, np.nan)

movie_data["vote_average"] = movie_data["vote_average"].replace(0, np.nan)

movie_data["vote_count"] = movie_data["vote_count"].replace(0, np.nan)

movie_data["popularity"] = movie_data["popularity"].replace(0, np.nan)

In [47]:
movie_data.isnull().sum().sort_values(ascending=False)

revenue                 1427
budget                  1037
tagline                  844
vote_average              63
vote_count                62
runtime                   37
overview                   3
release_date               1
popularity                 1
id                         0
genres                     0
production_countries       0
production_companies       0
original_language          0
original_title             0
keywords                   0
spoken_languages           0
status                     0
title                      0
dtype: int64

In [48]:
movie_data.duplicated().sum()

np.int64(0)

In [49]:
movie_data["id"].duplicated().sum()

np.int64(0)

In [50]:
movie_data["title"].duplicated().sum()

np.int64(3)

In [51]:
movie_data[movie_data["title"].duplicated(keep=False)][
    ["id", "title", "release_date"]
].sort_values("title")

         id            title release_date
1359    268           Batman   1989-06-23
4267   2661           Batman   1966-07-30
3647  39269  Out of the Blue   1980-05-01
3693  10844  Out of the Blue   2006-10-12
972   72710         The Host   2013-03-22
2877   1255         The Host   2006-07-27

In [52]:
movie_data["release_date"] = pd.to_datetime(
    movie_data["release_date"],
    errors="coerce"
)

In [53]:
movie_data["release_date"].dtype

dtype('<M8[ns]')

In [54]:
movie_data["release_date"].isnull().sum()

np.int64(1)

In [55]:
movie_data["release_year"] = movie_data["release_date"].dt.year

In [57]:
movie_data[["title", "release_date", "release_year"]].head(10)

                                      title release_date  release_year
0                                    Avatar   2009-12-10        2009.0
1  Pirates of the Caribbean: At World's End   2007-05-19        2007.0
2                                   Spectre   2015-10-26        2015.0
3                     The Dark Knight Rises   2012-07-16        2012.0
4                               John Carter   2012-03-07        2012.0
5                              Spider-Man 3   2007-05-01        2007.0
6                                   Tangled   2010-11-24        2010.0
7                   Avengers: Age of Ultron   2015-04-22        2015.0
8    Harry Potter and the Half-Blood Prince   2009-07-07        2009.0
9        Batman v Superman: Dawn of Justice   2016-03-23        2016.0

In [58]:
movie_data["release_year"].isnull().sum()

np.int64(1)

In [59]:
movie_data.describe().T

,count,mean,min,25%,50%,75%,max,std
budget,3766.0,37042837.631705,1.0,8000000.0,23000000.0,50000000.0,380000000.0,42646514.43559
id,4803.0,57165.484281,5.0,9014.5,14629.0,58610.5,459488.0,88694.614033
popularity,4802.0,21.496776,0.000372,4.671734,12.924931,28.332017,875.581305,31.818451
release_date,4802,2002-12-27 23:45:54.352353280,1916-09-04 00:00:00,1999-07-14 00:00:00,2005-10-03 00:00:00,2011-02-16 00:00:00,2017-02-03 00:00:00,NaN
revenue,3376.0,117031352.915877,5.0,15352895.25,51751835.0,140165095.5,2787965087.0,183483090.417008
runtime,4766.0,107.660722,14.0,94.0,104.0,118.0,338.0,20.749424
vote_average,4740.0,6.173143,0.5,5.6,6.2,6.8,10.0,0.972684
vote_count,4741.0,699.244252,1.0,58.0,242.0,750.0,13752.0,1240.091227
release_year,4802.0,2002.468763,1916.0,1999.0,2005.0,2011.0,2017.0,12.414354

In [60]:
movie_data["vote_average"].describe()

count    4740.000000
mean        6.173143
std         0.972684
min         0.500000
25%         5.600000
50%         6.200000
75%         6.800000
max        10.000000
Name: vote_average, dtype: float64